### PR TITLE
Issue #1 | Render names of items in shopping list

### LINKED ISSUE #1: 1. As a user, I want to read the names of all of the items in my shopping list
## Summary

The most important feature of our app is the ability to look at what's on the list, so the user knows what they need to buy. The `List` component is the best place in our code to do that. In fact, this feature is already partially implemented. Refer to the acceptance criteria in this issue, and the existing code, to understand the work that remains.

The `List` component is rendered on the `/list` page. Because the navigation links are currently broken, you'll have to type that path into your browser's address bar.

## Acceptance criteria
- [x] The `streamListItems` function is used in `App.jsx` to get the items in the current list from the Firestore database
- [x] The list is passed into the `List` component as a prop named `data`
- [x] In `List.jsx`, the `ListItem` component is used to render the name of each item

## Notes
- ⚠️ Your **only goal** is to make sure that the names of the items render as expected. You might be tempted to modify `ListItem.jsx` to show more information – you will do that **later**. If you want a peek at the future, [this wireframe](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-populated.png) is what your list could look like closer to the end of the project.
- The data you need is already being passed into the `List` component. What steps do you need to take in order to render it?

### PR DESCRIPTION
**Pull request by shannonerhea**
## Description

This PR adds the ListItem component to List.jsx to render the names of items on the list. Update Firebase config in config.js to connect DB). 

## Related Issue

Closes #1 

## Acceptance Criteria

 The streamListItems function is used in App.jsx to get the items in the current list from the Firestore database
 The list is passed into the List component as a prop named data
 In List.jsx, the ListItem component is used to render the name of each item

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
Screen Shot 2023-08-16 at 12 14 22 PM

### After

https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/86745260/00d8fd95-2623-4b0e-b51a-2670a313929e

## Testing Steps / QA Criteria

-From your terminal, pull down this branch with git pull origin is-sb-rendering-list-item-names and check that branch out with git checkout is-sb-rendering-list-item-names.
-run application using command npm start.
-add /list to URL to render updated list names (localhost:3000/list).

### CODE REVIEW

**Review by patty-rose — APPROVED** [review]
The branch changes work on my end and they look right to me. Great work with your first PR!
I’m not sure this calls for redoing anything but I have a couple best practice notes based on my own experiences with having my code reviewed:
- the package-lock.json is included in this PR -- I don’t think it’s necessary and I’m under the impression we want to avoid pushing this file.
- Considering the scope of these changes, I wouldn’t expect this PR to have 7 commits. 1 or 2 commits that address the config.js file changes as well as the List.jsx changes seem sufficient-- I think having concise organized commits can be really impressive when you are completing take-home technical challenges.

I hope this is helpful! I think you can move this to the next stage! :tada:

**Review by lydiadunning — CHANGES_REQUESTED** [review]
The list of names renders successfully, fulfilling the acceptance criteria for this issue.

However, the developer console shows the error message "Warning: Each child in a list should have a unique "key" prop." 
List renders ListItems without keys. The list works without keys, but could cause problems down the line, when the items in the list change.

**Comment by MikeBLambert** [comment]
> The branch changes work on my end and they look right to me. Great work with your first PR! I’m not sure this calls for redoing anything but I have a couple best practice notes based on my own experiences with having my code reviewed:
> 
> * the package-lock.json is included in this PR -- I don’t think it’s necessary and I’m under the impression we want to avoid pushing this file.
> * Considering the scope of these changes, I wouldn’t expect this PR to have 7 commits. 1 or 2 commits that address the config.js file changes as well as the List.jsx changes seem sufficient-- I think having concise organized commits can be really impressive when you are completing take-home technical challenges.
> 
> I hope this is helpful! I think you can move this to the next stage! 🎉

Such great comments @patty-rose ! 

**Should we commit the`package-lock.json`?**
It depends!

There are lots of things that can cause this file to change. Here are what I think the most common reasons:
1. **A new dependency was added in `package.json`**-  In this case, you almost certainly want to commit the new `package-lock.json`.
2. **Minor or patch version upgrades -** If you look in the `package.json`, you'll notice that there's a `^` or `~` next to versions of each dependency. These are saying that you want to automatically update  the dependency to any new minor or patch versions on the next `npm install`. [Here's a good article on it](https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/). Essentially, if there are dependencies that have come out with new minor or patch versions since the last time you ran `npm install`, then you'll likely have changes to the `package-lock.json`.
3. **Installing with a different node version** - generally, we want to be on the same version of node, which is what the `.nvmrc` file is supposed to be enforcing. You can check your version of node with the `node -v` command. `.nvmrc` indicates has `lts/*`, which I think means that we should be on the latest version, which would be version 20.

I think that we can rule out 1 b/c there are no new dependencies installed.
We can also probably rule out 2 b/c when I go onto the `main` branch and run `npm install`, I don't get a change to the `package-lock.json`.

So, I'm guessing that option 3 is the cause. @isaiahasanchez @shannonerhea. Do you know what version of `node` you had running when you ran `npm install`?

If it was v20, then I'm not sure why there's this change. 🤷 

If it's not v20, we'll probably want to switch to that. We can use `nvm` to manage our node versions.   [Here are install instructions](https://github.com/nvm-sh/nvm#install--update-script). Once it's installed, you can use `nvm install 20` to install that version. `nvm use <version-number>` will let you switch between versions. Once you've switched to v20, you can re-run `npm install` and then commit and push the change. :-)

I'd be happy to jump on a call to help out with any of this!

**Commits**
This is a stupendous callout @patty-rose!

I think @patty-rose is totally right that having well-organized and concise commits are great. However, it's also not great to have too few commits when there are lots of changes. At my company, we do look at the commits on the take-home projects for interviews. Usually, we're looking for clear messages (great job on that!) and organization (like did they commit features in manageable chunks rather than adding a single commit for the entire project). 

On this project though, I wouldn't worry about having a ton of commits while troubleshooting things. That happens all the time and if you look at my commits at work, you'd probably see lots of `"troubleshooting"` or `"triggering pipeline"` messages. Haha. 

There are lots of different strategies that can be used such as [squashing commits](https://www.git-tower.com/learn/git/faq/git-squash/) or reverting troubleshooting commits, which we can cover during a future office hours. :-)

**Comment by isaiahasanchez** [comment]
> > The branch changes work on my end and they look right to me. Great work with your first PR! I’m not sure this calls for redoing anything but I have a couple best practice notes based on my own experiences with having my code reviewed:
> > 
> > * the package-lock.json is included in this PR -- I don’t think it’s necessary and I’m under the impression we want to avoid pushing this file.
> > * Considering the scope of these changes, I wouldn’t expect this PR to have 7 commits. 1 or 2 commits that address the config.js file changes as well as the List.jsx changes seem sufficient-- I think having concise organized commits can be really impressive when you are completing take-home technical challenges.
> > 
> > I hope this is helpful! I think you can move this to the next stage! 🎉
> 
> Such great comments @patty-rose !
> 
> **Should we commit the`package-lock.json`?** It depends!
> 
> There are lots of things that can cause this file to change. Here are what I think the most common reasons:
> 
> 1. **A new dependency was added in `package.json`**-  In this case, you almost certainly want to commit the new `package-lock.json`.
> 2. **Minor or patch version upgrades -** If you look in the `package.json`, you'll notice that there's a `^` or `~` next to versions of each dependency. These are saying that you want to automatically update  the dependency to any new minor or patch versions on the next `npm install`. [Here's a good article on it](https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/). Essentially, if there are dependencies that have come out with new minor or patch versions since the last time you ran `npm install`, then you'll likely have changes to the `package-lock.json`.
> 3. **Installing with a different node version** - generally, we want to be on the same version of node, which is what the `.nvmrc` file is supposed to be enforcing. You can check your version of node with the `node -v` command. `.nvmrc` indicates has `lts/*`, which I think means that we should be on the latest version, which would be version 20.
> 
> I think that we can rule out 1 b/c there are no new dependencies installed. We can also probably rule out 2 b/c when I go onto the `main` branch and run `npm install`, I don't get a change to the `package-lock.json`.
> 
> So, I'm guessing that option 3 is the cause. @isaiahasanchez @shannonerhea. Do you know what version of `node` you had running when you ran `npm install`?
> 
> If it was v20, then I'm not sure why there's this change. 🤷
> 
> If it's not v20, we'll probably want to switch to that. We can use `nvm` to manage our node versions. [Here are install instructions](https://github.com/nvm-sh/nvm#install--update-script). Once it's installed, you can use `nvm install 20` to install that version. `nvm use <version-number>` will let you switch between versions. Once you've switched to v20, you can re-run `npm install` and then commit and push the change. :-)
> 
> I'd be happy to jump on a call to help out with any of this!
> 
> **Commits** This is a stupendous callout @patty-rose!
> 
> I think @patty-rose is totally right that having well-organized and concise commits are great. However, it's also not great to have too few commits when there are lots of changes. At my company, we do look at the commits on the take-home projects for interviews. Usually, we're looking for clear messages (great job on that!) and organization (like did they commit features in manageable chunks rather than adding a single commit for the entire project).
> 
> On this project though, I wouldn't worry about having a ton of commits while troubleshooting things. That happens all the time and if you look at my commits at work, you'd probably see lots of `"troubleshooting"` or `"triggering pipeline"` messages. Haha.
> 
> There are lots of different strategies that can be used such as [squashing commits](https://www.git-tower.com/learn/git/faq/git-squash/) or reverting troubleshooting commits, which we can cover during a future office hours. :-)



I thought I was on the latest node version but upon checking, I found out I was on version 18 so I just updated to the latest version. Do I need to do something immediately to update my code?

**Comment by MikeBLambert** [comment]
> 

@isaiahasanchez On this branch just run `npm install` and the push the changes to the `package-lock.json`

**Comment by shannonerhea** [comment]
@MikeBLambert @isaiahasanchez My Node was also out of date. I've updated Node to 20, should I push as well?

**Comment by MikeBLambert** [comment]
> The list of names renders successfully, fulfilling the acceptance criteria for this issue.
> 
> However, the developer console shows the error message "Warning: Each child in a list should have a unique "key" prop." List renders ListItems without keys. The list works without keys, but could cause problems down the line, when the items in the list change.

@lydiadunning Love that you found this! Here's a 

> @MikeBLambert @isaiahasanchez My Node was also out of date. I've updated Node to 20, should I push as well?

Absolutely! Push away!

**Comment by shannonerhea** [comment]
> The list of names renders successfully, fulfilling the acceptance criteria for this issue.
> 
> However, the developer console shows the error message "Warning: Each child in a list should have a unique "key" prop." List renders ListItems without keys. The list works without keys, but could cause problems down the line, when the items in the list change.

Good catch @lydiadunning Thank you! @isaiahasanchez we should definitely add a key

**Review by lydiadunning — APPROVED** [review]

**Review by MikeBLambert — APPROVED** [review]
Great work on the code, the beautiful PR description, and working through the great suggestions from the rest of the team!

**Pull request merged**
