### PR TITLE
Issue #2 | Add NavLinks to Layout

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by patty-rose**
## Description

This PR adds NavLinks for Home, List, and Add-Item in the Navbar in Layout.jsx.

## Related Issue

Closes #2 

## Acceptance Criteria

- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/101524326/f00186a7-a6c6-4e66-89d6-825f15699606

### After

https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/101524326/9c404323-04b9-4b66-9d6b-f2ce86d1a9e4

## Testing Steps / QA Criteria

-From your terminal, pull down this branch with git pull origin add-navlinks-to-layout and check that branch out with git checkout add-navlinks-to-layout.
-run application using command npm run start.
-click links at the bottom of the page to confirm they are working.
- [ ] Home link
-  [ ] List link
-  [ ] Add-Item link

### CODE REVIEW

**Comment by shannonerhea** [comment]
Excellent work!!

**Review by shannonerhea — APPROVED** [review]
Code is clean and easy to read. Great job!

**Comment by isaiahasanchez** [comment]
Looks good!

**Review by isaiahasanchez — APPROVED** [review]
Changes look good.

**Review by MikeBLambert — APPROVED** [review]
Such a great looking PR!!!

All of the AC is hit and everything works great!

For the testing steps, one cool thing that we have set up is preview URL, which is added automagically as a comment in the PR so reviewers can actually test your changes without pulling down and running the code locally. :-) 🥳  

Screenshot of preview URL

Everything looks GREAT!

**Pull request merged**
